### ISSUE TITLE
Implement fallback authors meta info

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/cff-maven-plugin#6]
Currently, eating its own dog food, the plugin doesn't create author info for some dependencie, e.g.,

```yaml
references:
- type: software
  title: AOP alliance (aopalliance)
  version: '1.0'
  license: OTHER
```

It is generally thought to be good practice that for these cases, the authors should be an abstract entity, i.e., `The {software title} {optionally: software version} team`.

The plugin should implement this.
